Content:

  Global:
  
    main:                   # the main module is required, and must not be removed.
      components:
        header:
        footer:
  
  
  
  Blog:  
    article: 
      page:         true
      components:  
        list:  
        show:  
        listCursus:
        listByTag:      { filters: dmTag }
        listBySkill:    { filters: Skill } 
        listAsBox: 
        
    skill:
      page:         true
      components:
        list: