<?php

/**
 * BaseSkill
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $experience
 * @property Doctrine_Collection $Articles
 * @property Doctrine_Collection $ArticlesSkills
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getName()           Returns the current record's "name" value
 * @method integer             getExperience()     Returns the current record's "experience" value
 * @method Doctrine_Collection getArticles()       Returns the current record's "Articles" collection
 * @method Doctrine_Collection getArticlesSkills() Returns the current record's "ArticlesSkills" collection
 * @method Skill               setId()             Sets the current record's "id" value
 * @method Skill               setName()           Sets the current record's "name" value
 * @method Skill               setExperience()     Sets the current record's "experience" value
 * @method Skill               setArticles()       Sets the current record's "Articles" collection
 * @method Skill               setArticlesSkills() Sets the current record's "ArticlesSkills" collection
 * 
 * @package    zazabe
 * @subpackage model
 * @author     Michel Meyer
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSkill extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('skill');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('experience', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Article as Articles', array(
             'refClass' => 'ArticleSkill',
             'local' => 'skill_id',
             'foreign' => 'article_id'));

        $this->hasMany('ArticleSkill as ArticlesSkills', array(
             'local' => 'id',
             'foreign' => 'skill_id'));

        $dmsortable0 = new Doctrine_Template_DmSortable();
        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             'rootColumnName' => 'root_id',
             ));
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $timestampable1 = new Doctrine_Template_Timestampable();
        $i18n0->addChild($timestampable1);
        $this->actAs($dmsortable0);
        $this->actAs($nestedset0);
        $this->actAs($i18n0);
    }
}