<?php

/**
 * BaseArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $extract
 * @property clob $body
 * @property integer $author
 * @property boolean $is_active
 * @property DmUser $Author
 * @property Doctrine_Collection $Skills
 * @property Doctrine_Collection $ArticlesSkills
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getTitle()          Returns the current record's "title" value
 * @method string              getExtract()        Returns the current record's "extract" value
 * @method clob                getBody()           Returns the current record's "body" value
 * @method integer             getAuthor()         Returns the current record's "author" value
 * @method boolean             getIsActive()       Returns the current record's "is_active" value
 * @method DmUser              getAuthor()         Returns the current record's "Author" value
 * @method Doctrine_Collection getSkills()         Returns the current record's "Skills" collection
 * @method Doctrine_Collection getArticlesSkills() Returns the current record's "ArticlesSkills" collection
 * @method Article             setId()             Sets the current record's "id" value
 * @method Article             setTitle()          Sets the current record's "title" value
 * @method Article             setExtract()        Sets the current record's "extract" value
 * @method Article             setBody()           Sets the current record's "body" value
 * @method Article             setAuthor()         Sets the current record's "author" value
 * @method Article             setIsActive()       Sets the current record's "is_active" value
 * @method Article             setAuthor()         Sets the current record's "Author" value
 * @method Article             setSkills()         Sets the current record's "Skills" collection
 * @method Article             setArticlesSkills() Sets the current record's "ArticlesSkills" collection
 * 
 * @package    zazabe
 * @subpackage model
 * @author     Michel Meyer
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticle extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('extract', 'string', 2000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 2000,
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             'extra' => 'markdown',
             ));
        $this->hasColumn('author', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DmUser as Author', array(
             'local' => 'author',
             'foreign' => 'id'));

        $this->hasMany('Skill as Skills', array(
             'refClass' => 'ArticleSkill',
             'local' => 'article_id',
             'foreign' => 'skill_id'));

        $this->hasMany('ArticleSkill as ArticlesSkills', array(
             'local' => 'id',
             'foreign' => 'article_id'));

        $dmgallery0 = new Doctrine_Template_DmGallery();
        $dmsortable0 = new Doctrine_Template_DmSortable();
        $dmtaggable0 = new Doctrine_Template_DmTaggable();
        $dmcommentable0 = new Doctrine_Template_DmCommentable();
        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             'rootColumnName' => 'root_id',
             ));
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'extract',
              2 => 'body',
              3 => 'is_active',
             ),
             ));
        $timestampable1 = new Doctrine_Template_Timestampable();
        $i18n0->addChild($timestampable1);
        $dmversionable1 = new Doctrine_Template_DmVersionable();
        $i18n0->addChild($dmversionable1);
        $this->actAs($dmgallery0);
        $this->actAs($dmsortable0);
        $this->actAs($dmtaggable0);
        $this->actAs($dmcommentable0);
        $this->actAs($nestedset0);
        $this->actAs($i18n0);
    }
}