<?php

/**
 * BaseArticleSkill
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $article_id
 * @property integer $skill_id
 * @property Article $Article
 * @property Skill $Skill
 * 
 * @method integer      getArticleId()  Returns the current record's "article_id" value
 * @method integer      getSkillId()    Returns the current record's "skill_id" value
 * @method Article      getArticle()    Returns the current record's "Article" value
 * @method Skill        getSkill()      Returns the current record's "Skill" value
 * @method ArticleSkill setArticleId()  Sets the current record's "article_id" value
 * @method ArticleSkill setSkillId()    Sets the current record's "skill_id" value
 * @method ArticleSkill setArticle()    Sets the current record's "Article" value
 * @method ArticleSkill setSkill()      Sets the current record's "Skill" value
 * 
 * @package    zazabe
 * @subpackage model
 * @author     Michel Meyer
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticleSkill extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article_skill');
        $this->hasColumn('article_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('skill_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Article', array(
             'local' => 'article_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Skill', array(
             'local' => 'skill_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}