default:
  
  http_metas:
    content-type: text/html

  stylesheets:  
    - /themeZazabe2/syntax-highlighter/styles/shCore.css
    - /themeZazabe2/syntax-highlighter/styles/shThemeDefault.css
    - /themeZazabe2/css/redmond/jquery-ui.css

    - reset  
    - global
    - navigation
    - boxes
    - colorbox  

    - main

    - print-demo
    - print: { media: print }
    
    
    

  javascripts:
    - /themeZazabe2/js/jquery-ui.js
    
    - /themeZazabe2/syntax-highlighter/scripts/shCore.js
    - /themeZazabe2/syntax-highlighter/scripts/shAutoloader.js
    
    - /themeZazabe2/syntax-highlighter/scripts/shBrushXml.js
    - /themeZazabe2/syntax-highlighter/scripts/shBrushJScript.js
    - /themeZazabe2/syntax-highlighter/scripts/shBrushPhp.js
    - /themeZazabe2/syntax-highlighter/scripts/shBrushCss.js
    
    - /themeZazabe2/js/qcolor.js
    - /themeZazabe2/js/qtime.js
    - /themeZazabe2/js/qbox.js
    

    - /themeZazabe2/js/jquery-colorbox.js
    - /themeZazabe2/js/jquery-qtip.js
    - /themeZazabe2/js/skillable.js
    - /themeZazabe2/js/bg-printable.js

    - /themeZazabe2/js/examples.js
    - /themeZazabe2/js/main.js
    
    - /themeZazabe2/js/browser-warning.min.js
    
    
  has_layout:     true
  layout:         layout
