default:
  
  http_metas:
    content-type: text/html

  stylesheets:  
    - /themeZazabe2/syntax-highlighter/css/syntax.css

    - reset  
    - global
    - navigation
    - boxes
    - colorbox  

    - main
    
    - print-demo
    - print: { media: print }
    
    
    

  javascripts:
    - /themeZazabe2/js/jquery-ui.js
    - /themeZazabe2/js/jquery-image-loader.js

    - /themeZazabe2/syntax-highlighter/js/shCore.js
    - /themeZazabe2/syntax-highlighter/js/shBrushSql.js
    - /themeZazabe2/syntax-highlighter/js/shBrushJScript.js
    - /themeZazabe2/syntax-highlighter/js/shBrushPhp.js
    - /themeZazabe2/syntax-highlighter/js/shBrushCss.js
    - /themeZazabe2/syntax-highlighter/js/shBrushXml.js
    - /themeZazabe2/syntax-highlighter/js/shBrushCpp.js


    - /themeZazabe2/js/draw.js
    - /themeZazabe2/js/boxes.js
    - /themeZazabe2/js/jquery-colorbox.js
    - /themeZazabe2/js/jquery-qtip.js
    - /themeZazabe2/js/skillable.js
    - /themeZazabe2/js/bg-printable.js

    - /themeZazabe2/js/main.js
    
    - /themeZazabe2/js/browser-warning.min.js
    - http://download.skype.com/share/skypebuttons/js/skypeCheck.js
    
    
  has_layout:     true
  layout:         layout