<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('article', 'gallery_id');
        $this->addColumn('article', 'gallery', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->addColumn('article', 'gallery_id', 'integer', '8', array(
             ));
        $this->removeColumn('article', 'gallery');
    }
}