<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('skills', 'skills_article_article_id', array(
             'name' => 'skills_article_article_id',
             'local' => 'article',
             'foreign' => 'id',
             'foreignTable' => 'article',
             ));
        $this->addIndex('skills', 'skills_article', array(
             'fields' => 
             array(
              0 => 'article',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('skills', 'skills_article_article_id');
        $this->removeIndex('skills', 'skills_article', array(
             'fields' => 
             array(
              0 => 'article',
             ),
             ));
    }
}