generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: Skill
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: skill
    with_doctrine_route: false
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - '=name'
          - experience
        sort:
          - position
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: true
      filter:
        display:
          - name
          - articles_list
          - experience
          - parent
      form:
        display:
          NONE: [name, experience]
          Others: [articles_list, parent]
        class: SkillAdminForm
        fields: {  }
      edit: ~
      new: ~
